#!/usr/bin/env python3
games = [
    ("Memory Match", "🧠", "Match pairs of cards", "game01"),
    ("Breakout", "🎯", "Break blocks with a bouncing ball", "game02"),
    ("Asteroids", "🌌", "Destroy asteroids in space", "game03"),
    ("Snake", "🐍", "Classic snake game", "game04"),
    ("Tetris", "🧩", "Stack falling blocks", "game05"),
    ("Flappy Bird", "🐦", "Fly through obstacles", "game06"),
    ("2048", "🔢", "Merge numbers to reach 2048", "game07"),
    ("Brick Breaker", "🧱", "Break all the bricks", "game08"),
    ("Space Invaders", "👾", "Defend Earth from aliens", "game09"),
    ("Frogger", "🐸", "Cross the road safely", "game10"),
    ("Bubble Shooter", "🫧", "Pop matching bubbles", "game11"),
    ("Match 3", "💎", "Match three in a row", "game12"),
    ("Word Search", "🔍", "Find hidden words", "game13"),
    ("Crossword", "📝", "Solve the crossword puzzle", "game14"),
    ("Sudoku", "9️⃣", "Fill the 9x9 grid", "game15"),
    ("Chess", "♟️", "Play chess", "game16"),
    ("Checkers", "⚫", "Play checkers", "game17"),
    ("Go", "⚪", "Ancient strategy game", "game18"),
    ("Reversi", "🔄", "Flip pieces to win", "game19"),
    ("Minesweeper", "💣", "Find all mines", "game20"),
    ("Solitaire", "🃏", "Classic card game", "game21"),
    ("Blackjack", "🃑", "Beat the dealer", "game22"),
    ("Poker", "🎰", "Play poker", "game23"),
    ("Roulette", "🎲", "Spin the wheel", "game24"),
    ("Slot Machine", "🎰", "Pull the lever", "game25"),
    ("Bingo", "🎯", "Mark your numbers", "game26"),
    ("Darts", "🎯", "Hit the bullseye", "game27"),
    ("Bowling", "🎳", "Knock down pins", "game28"),
    ("Golf", "⛳", "Sink the ball", "game29"),
    ("Basketball", "🏀", "Shoot hoops", "game30"),
    ("Soccer", "⚽", "Score goals", "game31"),
    ("Baseball", "⚾", "Hit home runs", "game32"),
    ("Tennis", "🎾", "Win the match", "game33"),
    ("Ping Pong", "🏓", "Table tennis", "game34"),
    ("Pool", "🎱", "Sink all balls", "game35"),
    ("Dodgeball", "🤾", "Dodge the balls", "game36"),
    ("Frisbee", "🥏", "Catch the frisbee", "game37"),
    ("Archery", "🏹", "Hit the target", "game38"),
    ("Fishing", "🎣", "Catch fish", "game39"),
    ("Cooking", "👨‍🍳", "Cook delicious meals", "game40"),
    ("Platformer", "🦘", "Jump and run", "game41"),
    ("Runner", "🏃", "Endless runner", "game42"),
    ("Racing", "🏎️", "Race to the finish", "game43"),
    ("Parking", "🅿️", "Park the car", "game44"),
    ("Flight", "✈️", "Fly the plane", "game45"),
    ("Helicopter", "🚁", "Pilot the helicopter", "game46"),
    ("Submarine", "🌊", "Navigate underwater", "game47"),
    ("Boat", "⛵", "Sail the seas", "game48"),
    ("Train", "🚂", "Drive the train", "game49"),
    ("Truck", "🚚", "Deliver cargo", "game50"),
    ("Taxi", "🚕", "Pick up passengers", "game51"),
    ("Bus", "🚌", "Drive the bus route", "game52"),
    ("Monster", "👹", "Fight monsters", "game53"),
    ("Zombie", "🧟", "Survive the zombies", "game54"),
    ("Vampire", "🧛", "Defeat vampires", "game55"),
    ("Ghost", "👻", "Catch the ghosts", "game56"),
    ("Dragon", "🐉", "Slay the dragon", "game57"),
    ("Wizard", "🧙", "Cast spells", "game58"),
    ("Knight", "🛡️", "Fight as a knight", "game59"),
    ("Ninja", "🥷", "Stealth mission", "game60"),
    ("Pirate", "🏴‍☠️", "Sail the high seas", "game61"),
    ("Cowboy", "🤠", "Wild west adventure", "game62"),
    ("Robot", "🤖", "Control the robot", "game63"),
    ("Alien", "👽", "Invade Earth", "game64"),
    ("UFO", "🛸", "Fly the UFO", "game65"),
    ("Rocket", "🚀", "Launch to space", "game66"),
    ("Moon", "🌙", "Land on the moon", "game67"),
    ("Mars", "🔴", "Explore Mars", "game68"),
    ("Star", "⭐", "Collect stars", "game69"),
    ("Planet", "🪐", "Explore planets", "game70"),
    ("Galaxy", "🌌", "Travel the galaxy", "game71"),
    ("Comet", "☄️", "Catch the comet", "game72"),
    ("Meteor", "☄️", "Avoid meteors", "game73"),
    ("Treasure", "💎", "Find the treasure", "game74"),
    ("Coin", "🪙", "Collect coins", "game75"),
    ("Gem", "💠", "Gather gems", "game76"),
    ("Jewel", "💍", "Collect jewels", "game77"),
    ("Diamond", "💎", "Mine diamonds", "game78"),
    ("Gold", "🥇", "Collect gold", "game79"),
    ("Silver", "🥈", "Gather silver", "game80"),
    ("Bronze", "🥉", "Find bronze", "game81"),
    ("Medal", "🏅", "Win medals", "game82"),
    ("Trophy", "🏆", "Earn trophies", "game83"),
    ("Crown", "👑", "Wear the crown", "game84"),
    ("Castle", "🏰", "Defend the castle", "game85"),
    ("Tower", "🗼", "Build the tower", "game86"),
    ("Bridge", "🌉", "Cross the bridge", "game87"),
    ("Mountain", "⛰️", "Climb the mountain", "game88"),
    ("Forest", "🌲", "Explore the forest", "game89"),
    ("Desert", "🏜️", "Cross the desert", "game90"),
    ("Island", "🏝️", "Survive the island", "game91"),
    ("Beach", "🏖️", "Relax on the beach", "game92"),
    ("Ocean", "🌊", "Dive into the ocean", "game93"),
    ("River", "🌊", "Navigate the river", "game94"),
    ("Lake", "🏞️", "Explore the lake", "game95"),
    ("Waterfall", "🌊", "Climb the waterfall", "game96"),
    ("Volcano", "🌋", "Escape the volcano", "game97"),
    ("Cave", "🕳️", "Explore the cave", "game98"),
    ("Crystal", "🔮", "Collect crystals", "game99"),
    ("Magic", "✨", "Use magic powers", "game100"),
    ("Fairy", "🧚", "Help the fairy", "game101"),
    ("Unicorn", "🦄", "Ride the unicorn", "game102"),
    ("Rainbow", "🌈", "Follow the rainbow", "game103"),
]

html_cards = []
for name, icon, desc, file in games:
    html_cards.append(f'''                <a href="{file}.html" class="game-card">
                    <div class="game-icon">{icon}</div>
                    <h3>{name}</h3>
                    <p>{desc}</p>
                </a>''')

with open('game_cards.txt', 'w', encoding='utf-8') as f:
    f.write('\n'.join(html_cards))

print('Generated game_cards.txt with all game cards')

